config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'logout' => "session#destroy" ,:as => 'logout'
  
  resources :users
  get 'sessions/login'
  resources :sessions
  resources :password_resets
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_create {generate_token(:auth_token)}
  before_save :encrypt_password
  after_save :clear_password
  validates :email,:presence => true,:uniqueness => true
  validates :name,:phone_number,:presence => true
  validates_length_of :name,:in=>8..16
  EMAIL_REGEX = /\A[A-za-z0-9.-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
  validates :email, :format => EMAIL_REGEX
  validates_format_of :phone_number ,:with => /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/
  validates_length_of :phone_number, :is => 10
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def clear_password
    self.password = nil
  end
  def self.authenticate(email,password)
    #if EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(email)
      #else
      #user=User.find_by_name(username_or_password)
      #end
    if (user && user.password_hash) == BCrypt::Engine.hash_secret(password , user.password_salt)
      return user
    else
      return false
    end
    #def match_password(login_password="")
     # encrypted_password == #BCrypt::Engine.hash_secret(login_password,salt)
    #end
  end
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:ath_token]
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  def create
  user = User.find_by_email(params[:email])
  user.send_password_reset if user
  redirect_to sessions_login_path, :notice => "Email sent with password reset instructions."
end

def edit
  @user = User.find_by_password_reset_token!(params[:id])
end

def update
  @user = User.find_by_password_reset_token!(params[:id])
  if @user.password_reset_sent < 2.hours.ago
    redirect_to new_password_reset_path, :alert => "Password reset has expired."
  elsif @user.update_attributes(params[:user].permit(:password))
    redirect_to sessions_login_path, :notice => "Password has been reset!"
  else
    render :edit
  end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end
  def create
    user = User.authenticate(params[:email],params[:password])
    #if authorized_user && user.authenticate(params[:password])
    if user
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to users_path ,:notice => "wow welcome again, you logged in as #{user.email}"
    else
      flash[:notice] = "invalid username or password"
      render "login"
    end
  end
  def destroy
    cookies.delete(:auth_token)
    redirect_to new_user_path , :notice => "successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:password,:gender,:email,:phone_number,:subject,:date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash#{name}" %>
        <% end %>

<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
    <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.radio_button :gender, 'male' , :checked => true %>
    <%= f.label :male ,'male'%>
    <%= f.radio_button :gender , 'female' %>
    <%= f.label :female ,'female'%>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email%>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :subject %>
    <%= f.select :subject , collection: ["physics" , "chemistry" , "maths"] ,prompt: "select your subject" %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth , :start_year => 1960 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    <tr>
    		<th>Name</th>
    		<th>Password_hash</th>
    		<th>Password_salt</th>
    		<th>email</th>
		<th>gender</th>
		<th>phone number</th>
		<th>subject</th>
		<th>DOB</th>
    		<th>Created_at</th>
    		<th>updated_at<th>
    		</tr></thead>
    
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      	<td><%= user.name %></td>
      	<td><%= user.password_hash %></td>
      	<td><%= user.password_salt %></td>
      	<td><%= user.email %></td>
      	<td><%= user.gender %></td>
      	<td><%= user.phone_number %></td>
	<td><%= user.subject %></td>
	<td><%= user.date_of_birth %></td>
	<td><%= user.created_at %></td>
	<td><%= user.updated_at %></td>
	      
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<strong>Name:</strong>
	<%= @user.name %>
</p>
<p>
	<strong>Password:</strong>
	<%= @user.password_hash %>
</p>
<p>
	<strong>Gender:</strong>
	<%= @user.gender %>
</p>
<p>
	<strong>Email:</strong>
	<%= @user.email %>
</p>
<p>
	<strong>Phone Number:</strong>
	<%= @user.phone_number %>
</p>
<p>
	<strong>Subject:</strong>
	<%= @user.subject %>
</p>
<p>
	<strong>Date of birth:</strong>
	<%= @user.date_of_birth %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>